### ISSUE TITLE
Does this method implement projection onto the input surface?

### ISSUE THREAD

**Issue by alecjacobson** [sgsellan/botsch-kobbelt-remesher-libigl#5]
If I run:

    ./precompiled/osx/bin/remeshmesh ~/Dropbox/models/wooden-chair-solid.obj bar.obj -i 3 -h 0.1

on this simple chair model 
[wooden-chair-solid.obj.zip](https://github.com/sgsellan/botsch-kobbelt-remesher-libigl/files/5465970/wooden-chair-solid.obj.zip)

<img width="706" alt="Screen Shot 2020-10-30 at 11 20 16 AM" src="https://user-images.githubusercontent.com/2241689/97723238-f3f66480-1aa1-11eb-8f70-83cd31b9096f.png">

the output is very smoothed and most new vertices are not lying on the original geometry:

<img width="706" alt="Screen Shot 2020-10-30 at 11 20 24 AM" src="https://user-images.githubusercontent.com/2241689/97723325-0a042500-1aa2-11eb-85c9-78e4d4f7255c.png">

**Comment by sgsellan** [comment]
It does now!
