### ISSUE TITLE
Installation problem related to numpyeigen

### ISSUE THREAD

**Issue by simon-cross** [sgsellan/botsch-kobbelt-remesher-libigl#9]
I have tried to install the code with CMake, but when I run `cmake ..`, I get the following error message:
```
CMake Error at CMakeLists.txt:23 (include):
  include could not find load file:

    numpyeigen

CMake Error at CMakeLists.txt:52 (npe_add_module):
  Unknown CMake command "npe_add_module".

-- Configuring incomplete, errors occurred!
```
I have installed Egein3 by downloading the code and running the following code:
```
mkdir build
cd build
cmake ..
make
sudo make install 
```

**Comment by bathal1** [comment]
Hi,

When cloning the repo, did you also checkout the submodules? i.e. `git clone --recursive`, or `git submodule update --init --recursive` if the repo has already been cloned

**Comment by simon-cross** [comment]
Thank you for your reply.

I did not clone the repository, I downloaded the zip file. Now, I have tried to run the following command:
`git clone --recursive git@github.com:sgsellan/botsch-kobbelt-remesher-libigl.git`
but I get the following error message:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by simon-cross** [comment]
Thank you for your reply.

I have succeded in compiling the code according to your recommendation.
